### ISSUE TITLE
NAP doesn't work

### ISSUE THREAD

**Issue by Jingxian-Ren** [DorresteinLaboratory/NAP_ProteoSAFe#4]
When I upload the data for nap and run the NAP tool on the web, the result showed an error below. What should I do to deal with the error?

Error in file(file, "rt") : cannot open the connection
Calls: write.table -> is.data.frame -> read.delim -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'metfrag_out/final_summary.txt': No such file or directory
Execution halted
Tool execution terminates abnormally with exit code [1]

**Comment by ridasilva** [comment]
HI @Jingxian-Ren, do you have the url from the job?
If you could post your question at the forum
https://groups.google.com/forum/#!forum/molecular_networking_bug_reports

it would help us.

**Comment by Jingxian-Ren** [comment]
OK， I will post the question there later. Thx

**Comment by Jingxian-Ren** [comment]
My job URL: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=e042626d5d5c4fea960e2f26c9db4a41

**Comment by rsilvabioinfo** [comment]
It seems you don't have any database selected, either select one or more
from here
COCONUT, GNPS, HMDB, SUPNAT, NPAtlas, CHEBI, DRUGBANK and FooDB

Or provide a file in the specified format. Take a look at the documentation
https://ccms-ucsd.github.io/GNPSDocumentation/nap/


Em qui., 9 de jun. de 2022 às 23:21, Jingxian-Ren ***@***.***>
escreveu:

**Comment by Jingxian-Ren** [comment]
Thanks a lot. The NAP is running well.
